#!/usr/bin/env python3
"""Fetch the YOLO26n COCO ONNX checkpoint for vision_pipeline integration tests.

This script is invoked at CMake configure time when
``-DROC_VISION_FETCH_TEST_MODELS=ON`` (the default).  It is intentionally
network-tolerant: any failure (no internet, mirror down, model not yet
published) is logged and the script exits cleanly with status 0 so the
CMake configure does not fail.  The Catch2 test suite checks for the
presence of the .onnx + .yaml at runtime and skips with a message if
they are absent — see ``tests/test_inference_engine.cpp``.

The script also writes ``yolo26n-coco.yaml``, ``yolo26m-roc-humanoid.yaml``,
and ``osnet-ain-x1-0.yaml`` reference manifests (idempotent — only writes
when missing) so the manifest-loader tests have real schema examples to
exercise on a fresh clone.
"""

from __future__ import annotations

import argparse
import os
import shutil
import sys
import urllib.error
import urllib.request
from pathlib import Path

# Authoritative YOLO26n ONNX mirrors.  We try each in order; the first that
# returns a HTTP 200 + non-empty body wins.  All URLs are CC-BY-NC for
# weights distribution per Ultralytics' license.
YOLO26N_URLS = [
    # Ultralytics primary release host (URL guessed from their YOLO11 naming
    # convention — may 404 if the YOLO26 release hasn't been pushed under this
    # exact slug yet, in which case the test simply skips).
    "https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo26n.onnx",
    "https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26n.onnx",
]


def write_if_missing(path: Path, contents: str) -> None:
    if not path.exists():
        path.write_text(contents, encoding="utf-8")
        print(f"  wrote {path.name}")


YOLO26N_COCO_MANIFEST = """\
# Auto-generated by fetch_yolo26n.py — DO NOT EDIT.
# Reference manifest for the YOLO26n COCO-pretrained model used by the
# vision_pipeline integration tests.  Per §3.3 of
# `phase_1_universal_ep_and_manifest.md`.

schema_version: 1

name:        yolo26n-coco
purpose:     detection
trained_on:  COCO 2017
notes:       Bring-up / smoke test for the ROC vision pipeline.

input:
  layout:           NCHW
  channel_order:    RGB
  expected_shape:   [1, 3, 640, 640]
  dtype:            float32
  normalization:
    scale:          0.00392156862745
    mean:           [0.0, 0.0, 0.0]
    std:            [1.0, 1.0, 1.0]
  preprocessing:
    letterbox:      true
    pad_value:      [114, 114, 114]
    pad_to:         model_input

output:
  head:             yolo26_detect
  format:           cxcywh_logits
  expected_shape:   [1, 84, 8400]
  num_classes:      80
  nms_in_graph:     false
  thresholds:
    score:          0.25

runtime_hints:
  preferred_ep:     DirectML
  precision:        fp16
  cache_compiled:   true

classes:
  - {id: 0,  name: person,        roc_label: Person}
  - {id: 1,  name: bicycle,       roc_label: Unknown}
  - {id: 2,  name: car,           roc_label: Unknown}
  - {id: 3,  name: motorcycle,    roc_label: Unknown}
  - {id: 4,  name: airplane,      roc_label: Unknown}
  - {id: 5,  name: bus,           roc_label: Unknown}
  - {id: 6,  name: train,         roc_label: Unknown}
  - {id: 7,  name: truck,         roc_label: Unknown}
  - {id: 8,  name: boat,          roc_label: Unknown}
  - {id: 9,  name: traffic_light, roc_label: Unknown}
  - {id: 10, name: fire_hydrant,  roc_label: Unknown}
  - {id: 11, name: stop_sign,     roc_label: Unknown}
  - {id: 12, name: parking_meter, roc_label: Unknown}
  - {id: 13, name: bench,         roc_label: Unknown}
  - {id: 14, name: bird,          roc_label: Unknown}
  - {id: 15, name: cat,           roc_label: Unknown}
  - {id: 16, name: dog,           roc_label: Unknown}
  - {id: 17, name: horse,         roc_label: Unknown}
  - {id: 18, name: sheep,         roc_label: Unknown}
  - {id: 19, name: cow,           roc_label: Unknown}
  - {id: 20, name: elephant,      roc_label: Unknown}
  - {id: 21, name: bear,          roc_label: Unknown}
  - {id: 22, name: zebra,         roc_label: Unknown}
  - {id: 23, name: giraffe,       roc_label: Unknown}
  - {id: 24, name: backpack,      roc_label: AccessoryBackpack}
  - {id: 25, name: umbrella,      roc_label: Unknown}
  - {id: 26, name: handbag,       roc_label: AccessoryBackpack}
  - {id: 27, name: tie,           roc_label: Unknown}
  - {id: 28, name: suitcase,      roc_label: Unknown}
  - {id: 29, name: frisbee,       roc_label: Unknown}
  - {id: 30, name: skis,          roc_label: Unknown}
  - {id: 31, name: snowboard,     roc_label: Unknown}
  - {id: 32, name: sports_ball,   roc_label: Unknown}
  - {id: 33, name: kite,          roc_label: Unknown}
  - {id: 34, name: baseball_bat,  roc_label: Unknown}
  - {id: 35, name: baseball_glove,roc_label: Unknown}
  - {id: 36, name: skateboard,    roc_label: Unknown}
  - {id: 37, name: surfboard,     roc_label: Unknown}
  - {id: 38, name: tennis_racket, roc_label: Unknown}
  - {id: 39, name: bottle,        roc_label: Unknown}
  - {id: 40, name: wine_glass,    roc_label: Unknown}
  - {id: 41, name: cup,           roc_label: Unknown}
  - {id: 42, name: fork,          roc_label: Unknown}
  - {id: 43, name: knife,         roc_label: Unknown}
  - {id: 44, name: spoon,         roc_label: Unknown}
  - {id: 45, name: bowl,          roc_label: Unknown}
  - {id: 46, name: banana,        roc_label: Unknown}
  - {id: 47, name: apple,         roc_label: Unknown}
  - {id: 48, name: sandwich,      roc_label: Unknown}
  - {id: 49, name: orange,        roc_label: Unknown}
  - {id: 50, name: broccoli,      roc_label: Unknown}
  - {id: 51, name: carrot,        roc_label: Unknown}
  - {id: 52, name: hot_dog,       roc_label: Unknown}
  - {id: 53, name: pizza,         roc_label: Unknown}
  - {id: 54, name: donut,         roc_label: Unknown}
  - {id: 55, name: cake,          roc_label: Unknown}
  - {id: 56, name: chair,         roc_label: Unknown}
  - {id: 57, name: couch,         roc_label: Unknown}
  - {id: 58, name: potted_plant,  roc_label: Unknown}
  - {id: 59, name: bed,           roc_label: Unknown}
  - {id: 60, name: dining_table,  roc_label: Unknown}
  - {id: 61, name: toilet,        roc_label: Unknown}
  - {id: 62, name: tv,            roc_label: Unknown}
  - {id: 63, name: laptop,        roc_label: Unknown}
  - {id: 64, name: mouse,         roc_label: Unknown}
  - {id: 65, name: remote,        roc_label: Unknown}
  - {id: 66, name: keyboard,      roc_label: Unknown}
  - {id: 67, name: cell_phone,    roc_label: Unknown}
  - {id: 68, name: microwave,     roc_label: Unknown}
  - {id: 69, name: oven,          roc_label: Unknown}
  - {id: 70, name: toaster,       roc_label: Unknown}
  - {id: 71, name: sink,          roc_label: Unknown}
  - {id: 72, name: refrigerator,  roc_label: Unknown}
  - {id: 73, name: book,          roc_label: Unknown}
  - {id: 74, name: clock,         roc_label: Unknown}
  - {id: 75, name: vase,          roc_label: Unknown}
  - {id: 76, name: scissors,      roc_label: Unknown}
  - {id: 77, name: teddy_bear,    roc_label: Unknown}
  - {id: 78, name: hair_drier,    roc_label: Unknown}
  - {id: 79, name: toothbrush,    roc_label: Unknown}
"""

YOLO26M_ROC_MANIFEST = """\
# Reference manifest for the production 6-class humanoid model.
# The .onnx itself is NOT distributed with this repo — custom training is
# required.  This file exists so the manifest-loader tests have a real
# schema example, AND so the engine fails fast with a useful error when
# the .onnx is missing.

schema_version: 1

name:        yolo26m-roc-humanoid
purpose:     detection
trained_on:  CrowdHuman+COCO-WB+PPE
notes:       Custom-trained for ROC AI Vision 6-class humanoid hierarchy.

input:
  layout:           NCHW
  channel_order:    RGB
  expected_shape:   [1, 3, 640, 640]
  dtype:            float32
  normalization:
    scale:          0.00392156862745
    mean:           [0.0, 0.0, 0.0]
    std:            [1.0, 1.0, 1.0]
  preprocessing:
    letterbox:      true
    pad_value:      [114, 114, 114]
    pad_to:         model_input

output:
  head:             yolo26_detect
  format:           cxcywh_logits
  expected_shape:   [1, 10, 8400]
  num_classes:      6
  nms_in_graph:     false
  thresholds:
    score:          0.25

runtime_hints:
  preferred_ep:     DirectML
  precision:        fp16
  cache_compiled:   true

classes:
  - {id: 0, name: person,        roc_label: Person}
  - {id: 1, name: head,          roc_label: Head}
  - {id: 2, name: upper_torso,   roc_label: UpperTorso}
  - {id: 3, name: hat,           roc_label: AccessoryHat}
  - {id: 4, name: vest,          roc_label: AccessoryHat}
  - {id: 5, name: backpack,      roc_label: AccessoryBackpack}
"""

OSNET_MANIFEST = """\
# Reference manifest for the OSNet-AIN x1.0 re-id extractor.
schema_version: 1

name:        osnet-ain-x1-0
purpose:     reid
trained_on:  MSMT17+Market1501+CUHK03 (multi-source)
notes:       128-D L2-normalised appearance embedding for DeepSORT.

input:
  layout:           NCHW
  channel_order:    RGB
  expected_shape:   [1, 3, 256, 128]
  dtype:            float32
  normalization:
    scale:          0.00392156862745
    mean:           [0.485, 0.456, 0.406]
    std:            [0.229, 0.224, 0.225]
  preprocessing:
    letterbox:      false
    pad_value:      []
    pad_to:         none

output:
  head:             osnet_reid
  format:           reid_embedding
  expected_shape:   [1, 128, -1]
  num_classes:      0
  nms_in_graph:     false

runtime_hints:
  preferred_ep:     DirectML
  precision:        fp16
  batchable:        true
"""


def try_download(url: str, dest: Path, timeout: float = 30.0) -> bool:
    print(f"  trying {url} ...", flush=True)
    try:
        with urllib.request.urlopen(url, timeout=timeout) as r:
            data = r.read()
        if not data or len(data) < 1024 * 100:
            print(f"  -> response too small ({len(data)} bytes), skipping")
            return False
        dest.write_bytes(data)
        print(f"  -> wrote {dest} ({len(data) / 1024 / 1024:.1f} MiB)")
        return True
    except urllib.error.HTTPError as e:
        print(f"  -> HTTP {e.code}: {e.reason}")
    except urllib.error.URLError as e:
        print(f"  -> URL error: {e.reason}")
    except (TimeoutError, OSError) as e:
        print(f"  -> network error: {e}")
    return False


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--output-dir", required=True, type=Path)
    args = p.parse_args()

    out = args.output_dir.resolve()
    out.mkdir(parents=True, exist_ok=True)
    print(f"[roc_vision::fetch_yolo26n] output-dir = {out}")

    # Reference manifests — idempotent.
    write_if_missing(out / "yolo26n-coco.yaml",        YOLO26N_COCO_MANIFEST)
    write_if_missing(out / "yolo26m-roc-humanoid.yaml", YOLO26M_ROC_MANIFEST)
    write_if_missing(out / "osnet-ain-x1-0.yaml",       OSNET_MANIFEST)

    # YOLO26n ONNX checkpoint.
    onnx_path = out / "yolo26n-coco.onnx"
    if onnx_path.exists() and onnx_path.stat().st_size > 1024 * 1024:
        print(f"  yolo26n-coco.onnx already present ({onnx_path.stat().st_size / 1024 / 1024:.1f} MiB); skipping")
        return 0

    for url in YOLO26N_URLS:
        if try_download(url, onnx_path):
            return 0

    print("  WARN: no mirror succeeded — yolo26n-coco.onnx will be absent.")
    print("        End-to-end inference tests will skip with a message at runtime.")
    return 0   # non-fatal — tests handle missing model gracefully


if __name__ == "__main__":
    sys.exit(main())
